### ISSUE TITLE
Contributor's Guide: Getting Started with Github and Gitbook

### ISSUE THREAD

**Issue by Faolain** [yearn/yearn-docs#102]
Ticket related to https://github.com/iearn-finance/docs/issues/85 as a prerequisite.

**Document:** Getting Started with Github and Gitbook: https://hackmd.io/4U35op0ORoGT24lzPhbGNQ?view

**Motivation:** Clearly guide a new user to being able to successfully contribute to Yearn documentation via Github and Gitbook.

**Rationale:** Git and by extension Github are somewhat intimidating and complicated to someone not familiar with coding. We should strive to make it as easy as possible for someone to feel comfortable and empowered to committing documentation with the least amount of cognitive overload possible.

**Comment by tracheopteryx** [comment]
There is a good getting started with git and github guide here to include https://github.com/iearn-finance/docs/issues/88

**Comment by Faolain** [comment]
Thanks trach! added in

**Comment by definn-farmer** [comment]
Added few comments
