### ISSUE TITLE
French Docs

### ISSUE THREAD

**Issue by Faolain** [yearn/yearn-docs#145]
https://hackmd.io/N7RnjcOUTVWtgLOMlLPzhQ - Governance
https://hackmd.io/VXND1ydCSwG8xrJrJJiU8Q - yUSD
https://hackmd.io/r6Z4aAYZQe2gIP4HfkUjsw - Defi Glossary

- DarkGhosty, Gustave Laurant, Cryptouf, Fibonacci

Sep 25 at 1:04 AM
Half way done - DarkGhosty

cryptouf Sep 28 at 12:07 PM
Je viens de faire Governance. Je le mets ici en PJ au format PDF ca te va ? Je suis un peu perdu sur cette plateforme

**Comment by cryptoouf-blog** [comment]
Hi faolain. i'm don't really understand how github work. I spoke with Dark on TG. I did all french translations (except the glossary ) I'll try to push  it this week to see how it work.

**Comment by Faolain** [comment]
No worries @cryptoouf-blog we'll go over it all together but for the time being, this should work no different than our Trello board. Instead of using the Trello we'll just use the board located at https://github.com/orgs/iearn-finance/projects/4 to organize our work :)

**Comment by SchenLong** [comment]
Finished french Translation.

**Comment by cryptoouf-blog** [comment]
Schen Long. Not sure when you started , and where... . But everything is done., Just need the glossary.

**Comment by SchenLong** [comment]
@cryptoouf-blog Hello, I took the hackmd progress, corrected typo on doc 1 and 2 and finished translation (was half translated on the collab platform). 

The glossary I am on it up to multisig wallet right now, making a pause and will finish the doc before end of day but it needs someone to review from scratch for typo and formatting.

Please make sure all collaborative documents are updated to avoid work duplication. Best.

**Comment by cryptoouf-blog** [comment]
I can double check. The problem is that on trello nobody was really
involved. so i just started working on gitbook and translated everything by
myself. The french branch was only added recently. and i was really busy.
But now, I'll push it to the main repository .

So please just do the Glossary, and then we can cohordined for typo and
formatting .

Are you on the doc TG group ? because we are coordinating from here . And
to my knowledge I was the only one to work on French translations ...

**Comment by SchenLong** [comment]
No I am not on the tg group, I was looking for you on TG but no chance, add me @Paulisson and we take it from there. You now can consider you ve got support on French Translation :) I ll be done with the glossary by end of day. Talk to you on telegram

**Comment by SchenLong** [comment]
Defi Glossary: Translation complete - Requires formatting and typo review.
