### ISSUE TITLE
[DOC-40] VoterProxy Strategy Diagram

### ISSUE THREAD

**Issue by philburrrt** [yearn/yearn-docs#247]
Strategy description:
https://github.com/yearn/yearn-meta/blob/master/data/strategies/VoterProxy.json
Use: 
https://usdml.nymm.app/ to create the diagram. 
Guide is here: 
https://hackmd.io/@L4RPoDo4SoWIvw-rvs9DZg/yearn-diagram-guide. 

Upload USDML code as a .dot file in https://github.com/yearn/yearn-meta/tree/master/schema

Please add corresponding [DOC-#] when submitting a pull request.

**Comment by vany365** [comment]
do we need diagrams for these meta type of strategies? this does not apply to any single vault and is kind of a secondary vault in the background
