### ISSUE TITLE
[DOC-37] StrategyVaultUSDC Strategy Diagram

### ISSUE THREAD

**Issue by philburrrt** [yearn/yearn-docs#249]
Strategy description:
https://github.com/yearn/yearn-meta/blob/master/data/strategies/StrategyVaultUSDC.json
Use: 
https://usdml.nymm.app/ to create the diagram. 
Guide is here: 
https://hackmd.io/@L4RPoDo4SoWIvw-rvs9DZg/yearn-diagram-guide. 

Upload USDML code as a .dot file in https://github.com/yearn/yearn-meta/tree/master/schema

If strategy exists in https://docs.yearn.finance/yearn-finance/yvaults/vaults-and-strategies then implement in the following format: 

\## Strategies
\### \<StrategyName>
Contract: <contract_url>
\!\[]\(\<imgur url>)

for imgur photos, you upload the image, make it public, right click, "open image in new tab" and then you get something like this: https://i.imgur.com/LCQ6kwG.jpeg

then find everywhere in the table that says \<StrategyName> replace the contract link with a link to jump to /###StrategyVaultUSDC header:
\[ \<StrategyName>](https://docs.yearn.finance/yearn-finance/yvaults/vaults-and-strategies#strategyvaultusdc)

Please add corresponding [DOC-#] when submitting a pull request.

**Comment by Sednaoui** [comment]
@philburrrt how did you envision to display or link the image?

**Comment by philburrrt** [comment]
@Sednaoui I think the best way right now is to make a header underneath the vault / strategy tables that's something like:
## Strategies 
### StrategyVaultUSDC
[]!(<imgur url>)

for imgur stuff, you just upload the image, make it public, right click, "open image in new tab" and then you get something like this: https://i.imgur.com/LCQ6kwG.jpeg

then find everywhere in the table that says StrategyVaultUSDC and hyperlink it like this:

[StrategyVaultUSDC](https://docs.yearn.finance/yearn-finance/yvaults/vaults-and-strategies#Strategies)

**Comment by Sednaoui** [comment]
> @Sednaoui I think the best way right now is to make a header underneath the vault / strategy tables that's something like:
> ## Strategies
> ### StrategyVaultUSDC
> 
> []!()
> 
> for imgur stuff, you just upload the image, make it public, right click, "open image in new tab" and then you get something like this: https://i.imgur.com/LCQ6kwG.jpeg
> 
> then find everywhere in the table that says StrategyVaultUSDC and hyperlink it like this:
> 
> [StrategyVaultUSDC](https://docs.yearn.finance/yearn-finance/yvaults/vaults-and-strategies#Strategies)

got it! thanks for the clarification

**Comment by philburrrt** [comment]
@Sednaoui no problem, also, i misplaced the ! ... should be \!\[]\(\<imgur url>\)
