### ISSUE TITLE
Brazilian Portuguese - All YIPs Summary

### ISSUE THREAD

**Issue by rokinot** [yearn/yearn-docs#280]
# All Yips Summary - Brazilian Portuguese
### Aprovadas

| Número | Título                             | Autor          |
| -------| --------                          | --------        |
| 34     | Adicionar Synthetix (SNX) às Vaults    | Substreight     |
| 51     | Definir a estrutura de taxas da Vault v2    | banteg, lehnberg, milkyklim, tracheopteryx     |
| 52     | Tornar estrategistas sócios com mais pele em jogo em prol das mentes gloriosas da Yearn    | banteg, lehnberg, milkyklim     |
| 54     | Formalização do Financiamento de Operações    | banteg, lehnberg, lex_node, milkyklim, tracheopteryx     |

### Implementadas

| Número | Título                            | Autor          |
| -------| --------                          | --------        |
|0|	Propósito e Diretrizes para YIPs|	Comunidade yEarn|
|1	|Emissão de mais YFI|	Andre Cronje|
|10|	Transição para votações exclusivamente com YFI |Rewkang|
|12	|Reduzindo o quórum para aceitação de propostas |	cp287|
|32	|Remover destruição de YFI	|Sunil Srivatsa|
|33	|Adicionar LINK às yVaults	|franklin|
|35|	Distribuir doações vs Compras de YFI	|Andre Cronje, Klim K|
|36	|Recompensas do sistema enquanto capital operacional	|Andre Cronje, iTo, n00b, Artem K|
|37	|Participar da governância da CRV e impulsionar as recompensas de CRV em 2.5x|Andre Cronje, Artem K|
|38	|Distribuir/Manter recompensas do Balancer|Klim K|
|39|	Adicionar yVault de tokens LP da pool sBTC da Curve|uhmpeps|
|40	|Substituir signatários inativos do multisig|	cp287, Artem K|
|41|Empoderar temporariamente membros do multisig|tracheopteryx, Joe Mahon, franklin501, Michael Anderson, Vance Spencer|
|44|	Aprimorar categorias de YIPs	|Sam Bacha|
|45	|Adicionar recompensas para propostas implementadas de YIPs|Sunil Srivatsa|
### Rejeitadas

| Número | Título                            | Autor          |
| -------| --------                          | --------        |
|2	|Destruir YFI por meio de taxas	|Andre Cronje|
|5	|Redução de emissão semanal de YFI|	Damir Bandalo|
|8	|Reduzir a emissão semanal de YFI pela metade, assim como o bitcoin	|steamer.eth|
|14	|Reserva de Recompensas da Yearn	|YieldBouncer|
|30	|Agenda de inflação de YFI|	Substreight, DeltaTiger, Hannes Graah, Daryl Lau, yfi_whale|
|31	|Distribuição da inflação de YFI	|Substreight, DeltaTiger, Hannes Graah, Daryl Lau|
|42	|Adicionar renBTC às yVaults|	Azeem|
|43|	Aprimorar categorias de YIPs|	Sam Bacha|

**Comment by philburrrt** [comment]
Merged, thanks
