### ISSUE TITLE
[INT2-15] yEarn - Portuguese

### ISSUE THREAD

**Issue by philburrrt** [yearn/yearn-docs#310]
Contributors guide:

https://hackmd.io/@ucVuhc2gShSGsOJwjaDvqg/ryslC-Hou

Assign yourself to this issue if you begin working on it.

Page to translate:

https://docs.yearn.finance/yearn-finance/earn

When you turn this into a pull request, please add the [INT2-xx] tag from the title

**Comment by rokinot** [comment]
Done here https://github.com/yearn/yearn-docs/pull/365.
