### ISSUE TITLE
[INT2-9] Introduction - Vietnamese

### ISSUE THREAD

**Issue by philburrrt** [yearn/yearn-docs#316]
Contributors guide: 

https://hackmd.io/@ucVuhc2gShSGsOJwjaDvqg/ryslC-Hou

Assign yourself to this issue if you begin working on it. 

Page to translate:

https://docs.yearn.finance/

When you turn this into a pull request, please add the [INT2-xx] tag from the title

**Comment by xy-cypher** [comment]
# Giới thiệu

Yearn Finance là một bộ các ứng dụng trong thế giới Tài chính Phi Tập trung (DeFi), cung cấp tính năng cho vay tổng hợp, tạo lãi suất và bảo hiểm trên chuỗi khối (blockchain) Ethereum. Giao thức Yearn Finance được duy trì bởi hàng loạt lập trình viên độc lập và do những người nắm giữ đồng YFI quản lý.

Bạn có thể xem tóm lược các ứng dụng cốt lõi, quá trình quản trị và liên kết đến những kênh trò chuyện sôi nổi của Yearn ngay dưới đây.

## Ứng dụng Cốt lõi

### Vault (Kho bạc)

Là các bể góp vốn, tự động mang lại lãi suất dựa theo cơ hội trên thị trường. Vault (Kho bạc) có lợi cho người dùng nhờ gộp chung phí gas (từ đó giảm bớt phí gas cho từng cá nhân), tự động hóa quá trình tạo lãi và tái cân bằng, cũng như tự khắc dịch chuyển vốn khi xuất hiện cơ hội mới. Người dùng bình thường cũng không cần kiến thức chuyên sâu về DeFi hay các giao thức ngầm, nên Vault (Kho bạc) giống như một hình thức tài khoản tiết kiệm hoặc chiến lược đầu tư phòng vệ.

### Earn (Kiếm tiền)

Là ứng dụng đầu tiên của Yearn, mang lại tính năng cho vay tổng hợp. Vốn được dịch chuyển tự động giữa dYdX, AAVE và Compound tùy theo giao thức nào có lãi suất cao nhất. Điều đó giúp tối ưu hóa hoàn toàn quá trình tích lãi cho người dùng bình thường, đảm bảo luôn luôn thu lời tối đa từ các nền tảng trên.

## Governance (Quản trị)

Hệ sinh thái Yearn do những người nắm giữ đồng YFI quản lý. Họ sẽ trình bày và biểu quyết các đề xuất ngoại-chuỗi (off-chain). Đề xuất nào với số đông ủng hộ \(&gt;50% lượng biểu quyết\) sẽ được thực hiện bởi một ví đa-ký ("multi-signature" hay "multisig") gồm 9 thành viên. Các thay đổi phải được ký bởi 6 trên 9 thành viên đó để đi vào hiện thực. Thành viên của ví đa-ký (multisig) do những người nắm giữ đồng YFI bầu lên và có thể thay đổi tùy theo biểu quyết quản trị trong tương lai. Xin vui lòng đến mục Câu Hỏi Thường Gặp (FAQ) của chúng tôi để xem [danh sách thành viên ví đa-ký (multisig)](https://docs.yearn.finance/faq#who-are-the-9-multisig-signers) và thêm thông tin chi tiết về [quá trình quản trị](https://docs.yearn.finance/faq#governance).

## Kênh Trao đổi

Diễn đàn Quản trị [https://gov.yearn.finance/](https://gov.yearn.finance/)

Discord [http://discord.yearn.finance](http://discord.yearn.finance)

Telegram [https://t.me/yearnfinance](https://t.me/yearnfinance)

Reddit [https://www.reddit.com/r/yearn_finance/](https://www.reddit.com/r/yearn_finance/)

**Comment by xy-cypher** [comment]
finished
