### ISSUE TITLE
[INT2-28] Governance and Operations - Vietnamese

### ISSUE THREAD

**Issue by philburrrt** [yearn/yearn-docs#325]
Contributors guide:

https://hackmd.io/@ucVuhc2gShSGsOJwjaDvqg/ryslC-Hou

Assign yourself to this issue if you begin working on it.

Page to translate:

https://docs.yearn.finance/governance/governance-and-operations

When you turn this into a pull request, please add the [INT2-xx] tag from the title

**Comment by xy-cypher** [comment]
working on this

**Comment by xy-cypher** [comment]
done
