### ISSUE TITLE
[INT2-30] Proposal Repository - Vietnamese

### ISSUE THREAD

**Issue by philburrrt** [yearn/yearn-docs#327]
Contributors guide:

https://hackmd.io/@ucVuhc2gShSGsOJwjaDvqg/ryslC-Hou

Assign yourself to this issue if you begin working on it.

Page to translate:

https://docs.yearn.finance/governance/proposal-repository

When you turn this into a pull request, please add the [INT2-xx] tag from the title

**Comment by xy-cypher** [comment]
# Tổng hợp các Đề xuất

Đề xuất Cải thiện Yearn (YIP), Đề xuất Ủy quyền Yearn (YDP) và Đề xuất Thăm dò Yearn (YSP) đều là các công cụ để những người nắm giữ Tôken sử dụng trong việc duy trì và phát triển giao thức này.

## Đã được duyệt

|Số|Tiêu đề|Tác giả|
|------|-----|------|
|[34](https://yips.yearn.finance/YIPS/yip-34)|Bổ sung Synthetix (SNX) vào yVault|[Substreight](https://github.com/substreight)|
|[52](https://yips.yearn.finance/YIPS/yip-52)|Khiến Chiến lược gia có Lý do Gắn bó và Hợp sức cùng những Bộ não Tuyệt vời của Yearn|[banteg](https://github.com/banteg), [lehnberg](https://github.com/lehnberg), [milkyklim](https://github.com/milkyklim)|

## Đã được thực hiện

|Số|Tiêu đề|Tác giả|
|------|-----|------|
|[0](https://yips.yearn.finance/YIPS/yip-0)|Mục tiêu và Đường lối của YIP|Cộng đồng Yearn|
|[1](https://yips.yearn.finance/YIPS/yip-1)|Tạo thêm đồng YFI|[Andre Cronje](https://github.com/andrecronje)|
|[10](https://yips.yearn.finance/YIPS/yip-10)|Chuyển công tác biểu quyết sang chỉ dùng đồng YFI|[Rewkang](https://github.com/rewkang)|
|[12](https://yips.yearn.finance/YIPS/yip-12)|Giảm số đại biểu tham dự tối thiểu để duyệt đề xuất|[cp287](https://github.com/illlefr4u)|
|[32](https://yips.yearn.finance/YIPS/yip-32)|Bỏ chức năng "đốt" đồng YFI|[Sunil Srivatsa](https://github.com/alphastorm)|
|[33](https://yips.yearn.finance/YIPS/yip-33)|Bổ sung đồng LINK vào yVault|[franklin](https://github.com/franklin501)|
|[35](https://yips.yearn.finance/YIPS/yip-35)|Trả lại Quyên góp vs Mua đồng YFI|[Andre Cronje](https://github.com/andrecronje),[Klim K](https://github.com/milkyklim)|
|[36](https://yips.yearn.finance/YIPS/yip-36)|Dùng thưởng từ hệ thống làm vốn duy trì hoạt động|[Andre Cronje](https://github.com/andrecronje), iTo, [n00b](https://github.com/jchi18), [Artem K](https://github.com/banteg)|
|[37](https://yips.yearn.finance/YIPS/yip-37)|Tham gia quản trị CRV và tăng thưởng CRV lên 2.5x|[Andre Cronje](https://github.com/andrecronje), [Artem K](https://github.com/banteg)|
|[38](https://yips.yearn.finance/YIPS/yip-38)|Phân phát / Giữ thưởng từ Balancer|[Klim K](https://github.com/milkyklim)|
|[39](https://yips.yearn.finance/YIPS/yip-39)|Thêm kho yVault cho Tôken LP của Bể Góp vốn Curve sBTC|[uhmpeps](https://github.com/az)|
|[40](https://yips.yearn.finance/YIPS/yip-40)|Thay thế những người ký ví chung (multisig) không hoạt động|[cp287](https://github.com/illlefr4u), [Artem K](https://github.com/banteg)|
|[41](https://yips.yearn.finance/YIPS/yip-41)|Tạm thời Trao quyền Ví chung (Multisig)|[tracheopteryx](https://github.com/tracheopteryx), [Joe Mahon](https://github.com/Substreight), [franklin501](https://github.com/franklin501), Michael Anderson, Vance Spencer|
|[44](https://yips.yearn.finance/YIPS/yip-44)|Cải thiện các loại YIP|[sam bacha](sam@freighttrust.com)|
|[45](https://yips.yearn.finance/YIPS/yip-45)|Thêm một khoản thưởng cho các đề xuất YIP được duyệt và thực hiện|[Sunil Srivatsa](https://github.com/alphastorm)|
|[51](https://yips.yearn.finance/YIPS/yip-51)|Lập Cấu trúc Phí của Kho (Vault) v2|[banteg](https://github.com/banteg), [lehnberg](https://github.com/lehnberg), [milkyklim](https://github.com/milkyklim), [tracheoptery](https://github.com/tracheopteryx)|
|[54](https://yips.yearn.finance/YIPS/yip-54)|Chính thức hóa Ngân quỹ Hoạt động|[banteg](https://github.com/banteg), [lehnberg](https://github.com/lehnberg), [lex_node](https://github.com/lex_node)|[milkyklim](https://github.com/milkyklim), [tracheopteryx](https://github.com/tracheopteryx)|
|[55](https://gov.yearn.finance/t/yip-55-formalize-the-yip-process/7959/7)|Chính thức hóa Tiến trình YIP|[franklin](https://github.com/franklin501)|
|[56](https://snapshot.org/#/yearn/proposal/Qmb6gBzjvgLMazSrQQGVcjutLNdkVyM2Lh6yckMzdoaHWZ)|BABY: Buyback & Build (Mua lại & Xây dựng)|[lex_node](https://github.com/lex_node), [tracheopteryx](https://github.com/tracheopteryx), [Artem K](https://github.com/banteg), [Klim K](https://github.com/milkyklim), [Ryan Watkins](https://twitter.com/RyanWatkins_), [lehnberg](https://github.com/lehnberg)|
|[57](https://snapshot.org/#/yearn/proposal/QmX8oYTSkaXSARYZn7RuQzUufW9bVVQtwJ3zxurWrquS9a)| Cấp vốn cho Tương lai của Yearn| [aleks-blockchaincap](https://gov.yearn.finance/u/aleks-blockchaincap/summary), [Artem K](https://github.com/banteg), [dudesahn](https://twitter.com/dudesahn), [ekrenzke](https://gov.yearn.finance/u/ekrenzke), [lehnberg](https://github.com/lehnberg), [Klim K](https://github.com/milkyklim), [Ryan Watkins](https://twitter.com/RyanWatkins_), [srs-parafi](https://gov.yearn.finance/u/srs-parafi/summary), [tracheopteryx](https://github.com/tracheopteryx), [vooncer](https://gov.yearn.finance/u/vooncer/summary), [yfi-cent](https://gov.yearn.finance/u/yfi-cent/summary)|
|[59](https://snapshot.org/#/yearn/proposal/QmdRCXH6BQpNcucoZqAtS5hQKjckE2428qiZoWjxmJXbs3)|Tạm thời Gia hạn Trao quyền cho Ví chung (Multisig)|[lehnberg](https://github.com/lehnberg)|
|[60](https://snapshot.org/#/ybaby.eth/proposal/QmNqAqRKMFcoRjaRYAKCVETij6sjJ4S1293kbpYDMVvcjB)|Các Airdrop vào Kho Yearn|[lehnberg](https://github.com/lehnberg)|
|[61](https://snapshot.org/#/ybaby.eth/proposal/QmSMyYeKrRpnA7Xn56o2NtbCUzxmhzCupL7LxMA1reXxq4)|Quản trị 2.0|[tracheopteryx](https://github.com/tracheopteryx), [lex_node](https://github.com/lex_node)|

## Đã bị phản đối

|Số|Tiêu đề|Tác giả|
|------|-----|------|
|[2](https://yips.yearn.finance/YIPS/yip-2)|"Đốt" đồng YFI để nhận lệ phí|[Andre Cronje](https://github.com/andrecronje)|
|[5](https://yips.yearn.finance/YIPS/yip-5)|Giảm cung đồng YFI hàng tuần|[Damir Bandalo](https://github.com/sikiriki12)|
|[8](https://yips.yearn.finance/YIPS/yip-8)|Giảm cung đồng YFI hàng tuần đi một nửa, tương tự như Bitcoin|steamer.eth|
|[14](https://yips.yearn.finance/YIPS/yip-14)|Dự trữ Thưởng Yearn|[YieldBouncer](https://github.com/yieldbouncer)|
|[30](https://yips.yearn.finance/YIPS/yip-30)|Lịch biểu Lạm phát đồng YFI|[Substreight](https://github.com/substreight), [DeltaTiger](https://github.com/deltatigernz), [Hannes Graah](https://github.com/Graadient), [Daryl lau](https://github.com/Daryllautk), yfi_whale|
|[31](https://yips.yearn.finance/YIPS/yip-31)|Phân bổ lượng Lạm phát của đồng YFI|[Substreight](https://github.com/substreight), [DeltaTiger](https://github.com/deltatigernz), [Hannes Graah](https://github.com/Graadient), [Daryl lau](https://github.com/Daryllautk)|
|[42](https://yips.yearn.finance/YIPS/yip-42)|Bổ sung RenBTC vào yVault|[Azeem](https://github.com/zu-ctrl)|
|[43](https://yips.yearn.finance/YIPS/yip-43)|Cải thiện các loại YIP|[sam bacha](sam@freighttrust.com)|

**Comment by philburrrt** [comment]
@xy-cypher good work ser, will get these up shortly

**Comment by xy-cypher** [comment]
finished
