### ISSUE TITLE
feat: introduction - russian [INT2-117]

### ISSUE THREAD

**Issue by philburrrt** [yearn/yearn-docs#531]
Contributors guide: 

https://docs.yearn.finance/contributors/working-on-docs

Assign yourself to this issue if you begin working on it. 

Page to translate:

https://docs.yearn.finance/ the readme

**Comment by Getmegone** [comment]
I`m afraid I can`t assign myself as I am not a part of this repo I guess. @philburrrt 
But I`m working on translation already

**Comment by philburrrt** [comment]
@Getmegone commenting is good, thanks
